import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/services.dart' show rootBundle;
import 'package:quality_line_erp/core/exporting/pdf_print_service.dart';
import 'package:quality_line_erp/core/printing/pdf_text_support.dart';

/// Customer-safe vehicle service card built only from the public service view.
class VehicleServiceCardPdfService {
  const VehicleServiceCardPdfService();

  Future<void> printCard({
    required Map<String, Object?> card,
    required bool arabic,
  }) async {
    final bytes = await build(card: card, arabic: arabic);
    final vehicle = _map(card['vehicle']);
    await PdfPrintService.print(
      fileName:
          'vehicle-service-card-${vehicle['carNumber'] ?? vehicle['id']}.pdf',
      bytes: bytes,
    );
  }

  Future<Uint8List> build({
    required Map<String, Object?> card,
    required bool arabic,
  }) async {
    arabic = PdfTextSupport.canonicalPdfArabic(arabic);
    final fonts = await PdfTextSupport.loadFonts();
    final presentation = buildPresentation(card);
    final vehicle = _map(presentation['vehicle']);
    final history = _list(presentation['maintenanceHistory']);
    String t(String ar, String en) => arabic ? ar : en;
    String clean(Object? value) => PdfTextSupport.sanitize(value);
    final document = pw.Document(
      title: clean(t('بطاقة خدمة المركبة', 'Vehicle Service Card')),
      theme: pw.ThemeData.withFont(base: fonts.regular, bold: fonts.bold),
    );
    final primary = PdfColor.fromHex('#123B49');
    final accent = PdfColor.fromHex('#C59B45');
    pw.MemoryImage? logo;
    try {
      final data = await rootBundle.load(
        'assets/images/khat_al_jawda_logo.jpg',
      );
      logo = pw.MemoryImage(data.buffer.asUint8List());
    } catch (_) {
      logo = null;
    }
    final generatedAt = DateTime.now().toLocal().toIso8601String();
    document.addPage(
      pw.MultiPage(
        textDirection: arabic ? pw.TextDirection.rtl : pw.TextDirection.ltr,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 10),
          decoration: pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: accent, width: 2)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Row(
                children: [
                  if (logo != null)
                    pw.SizedBox(width: 42, height: 42, child: pw.Image(logo)),
                  if (logo != null) pw.SizedBox(width: 8),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      PdfTextSupport.text(
                        clean(t('شركة خط الجودة', 'Quality Line Company')),
                        style: pw.TextStyle(
                          font: fonts.bold,
                          color: primary,
                          fontSize: 15,
                        ),
                      ),
                      PdfTextSupport.text(
                        clean('${t('وقت الإنشاء', 'Generated')}: $generatedAt'),
                        style: const pw.TextStyle(fontSize: 7),
                      ),
                    ],
                  ),
                ],
              ),
              PdfTextSupport.text(
                clean(t('بطاقة خدمة المركبة', 'Vehicle Service Card')),
                style: pw.TextStyle(font: fonts.bold, fontSize: 13),
              ),
            ],
          ),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            PdfTextSupport.text(
              clean(
                t(
                  'سجل خدمة صادر من نظام خط الجودة',
                  'Service record generated by Quality Line ERP',
                ),
              ),
              style: const pw.TextStyle(fontSize: 7),
            ),
            PdfTextSupport.text(
              '${context.pageNumber} / ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 7),
            ),
          ],
        ),
        build: (_) => [
          pw.SizedBox(height: 14),
          pw.Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              for (final entry in <String, Object?>{
                t('رقم المركبة', 'Vehicle No.'): vehicle['carNumber'],
                t('الماركة / الموديل', 'Brand / Model'):
                    '${vehicle['brand'] ?? ''} ${vehicle['model'] ?? ''}',
                t('السنة', 'Year'): vehicle['year'],
                t('رقم الشاصي', 'Chassis'): vehicle['chassis'],
                t('رقم اللوحة', 'Plate'): vehicle['plateNumber'],
                t('اللون', 'Color'): vehicle['color'],
              }.entries)
                pw.Container(
                  width: 245,
                  padding: const pw.EdgeInsets.all(8),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                  ),
                  child: PdfTextSupport.text(
                    '${clean(entry.key)}: ${clean(entry.value ?? '—')}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ),
            ],
          ),
          pw.SizedBox(height: 16),
          PdfTextSupport.text(
            clean(
              t('السجل الزمني للصيانة', 'Chronological Maintenance History'),
            ),
            style: pw.TextStyle(font: fonts.bold, color: primary, fontSize: 13),
          ),
          pw.SizedBox(height: 8),
          if (history.isEmpty)
            PdfTextSupport.text(
              clean(t('لا يوجد سجل صيانة.', 'No maintenance history.')),
            )
          else
            pw.TableHelper.fromTextArray(
              headers: <String>[
                clean(t('أمر الصيانة', 'Maintenance order')),
                clean(t('التاريخ/الوقت', 'Date / time')),
                clean(t('المسؤول', 'Responsible')),
                clean(t('صرف المواد', 'Material issue')),
                clean(t('الفاتورة', 'Invoice')),
                clean(t('الدفعات', 'Payments')),
                clean(t('الكلفة', 'Cost')),
                clean(t('العملة', 'Currency')),
              ],
              data: history
                  .map(
                    (order) => <String>[
                      clean(order['orderNumber'] ?? '—'),
                      clean(
                        order['maintenanceDate'] ?? order['createdAt'] ?? '—',
                      ),
                      clean(
                        order['responsibleUser'] ??
                            order['createdByName'] ??
                            '—',
                      ),
                      clean(_references(order['materialIssues'])),
                      clean(
                        _references(
                          order['invoiceReferences'],
                          fallback: order['invoiceNumber'],
                        ),
                      ),
                      clean(_references(order['paymentReferences'])),
                      clean('${order['totalCost'] ?? 0}'),
                      clean(order['currencyCode'] ?? '—'),
                    ],
                  )
                  .toList(growable: false),
              border: pw.TableBorder.all(color: PdfColors.grey300, width: .45),
              headerDecoration: pw.BoxDecoration(color: primary),
              headerStyle: pw.TextStyle(
                font: fonts.bold,
                color: PdfColors.white,
                fontSize: 6.7,
              ),
              cellStyle: const pw.TextStyle(fontSize: 6.5),
              cellPadding: const pw.EdgeInsets.all(4),
            ),
          pw.SizedBox(height: 12),
          for (final order in history)
            if (_list(order['customDetails']).isNotEmpty)
              pw.Container(
                margin: const pw.EdgeInsets.only(bottom: 8),
                padding: const pw.EdgeInsets.all(8),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  border: pw.Border(
                    left: pw.BorderSide(color: accent, width: 3),
                  ),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: <pw.Widget>[
                    PdfTextSupport.text(
                      clean(
                        '${order['orderNumber'] ?? '—'} — ${t('تفاصيل مخصصة', 'Custom details')}',
                      ),
                      style: pw.TextStyle(font: fonts.bold, fontSize: 9),
                    ),
                    pw.SizedBox(height: 4),
                    for (final detail in _list(order['customDetails']))
                      PdfTextSupport.text(
                        clean(
                          '• ${detail['title'] ?? '—'}: ${detail['description'] ?? ''}',
                        ),
                        style: const pw.TextStyle(fontSize: 7.5),
                      ),
                  ],
                ),
              ),
        ],
      ),
    );
    return document.save();
  }

  Map<String, Object?> buildPresentation(Map<String, Object?> card) {
    final rawVehicle = _map(card['vehicle']);
    const vehicleKeys = <String>{
      'carNumber',
      'brand',
      'model',
      'year',
      'chassis',
      'plateNumber',
      'color',
      'vehicleType',
      'status',
      'warehouseName',
      'customerName',
      'purchaseReference',
      'salesReference',
    };
    const orderKeys = <String>{
      'orderNumber',
      'opportunityNumber',
      'maintenanceDate',
      'workflowStage',
      'status',
      'pricingType',
      'customerName',
      'currencyCode',
      'salePrice',
      'paidAmount',
      'paymentStatus',
      'warehouseName',
      'stockIssueNumber',
      'stockIssueStatus',
      'invoiceNumber',
      'invoiceStatus',
      'notes',
      'cancelReason',
      'createdAt',
      'createdByName',
      'responsibleUser',
      'materialIssues',
      'invoiceReferences',
      'paymentReferences',
      'customDetails',
    };
    const itemKeys = <String>{
      'name',
      'quantity',
      'unitPrice',
      'lineType',
      'warehouseName',
    };
    return <String, Object?>{
      'vehicle': <String, Object?>{
        for (final entry in rawVehicle.entries)
          if (vehicleKeys.contains(entry.key)) entry.key: entry.value,
      },
      'maintenanceHistory': _list(card['maintenanceHistory'])
          .map(
            (order) => <String, Object?>{
              for (final entry in order.entries)
                if (orderKeys.contains(entry.key)) entry.key: entry.value,
              'materialIssues': _list(order['materialIssues']),
              'invoiceReferences': _list(order['invoiceReferences']),
              'paymentReferences': _list(order['paymentReferences']),
              'customDetails': _list(order['customDetails']),
              'items': _list(order['items'])
                  .map(
                    (item) => <String, Object?>{
                      for (final entry in item.entries)
                        if (itemKeys.contains(entry.key))
                          entry.key: entry.value,
                    },
                  )
                  .toList(growable: false),
            },
          )
          .toList(growable: false),
    };
  }

  static String _references(Object? raw, {Object? fallback}) {
    final rows = _list(raw);
    if (rows.isEmpty) return fallback?.toString() ?? '—';
    final values = <String>[];
    for (final row in rows) {
      final value = row['reference'] ?? row['voucherNumber'] ?? row['id'];
      if (value != null && value.toString().trim().isNotEmpty) {
        values.add(value.toString().trim());
      }
    }
    return values.isEmpty ? (fallback?.toString() ?? '—') : values.join(', ');
  }

  static Map<String, Object?> _map(Object? raw) =>
      raw is Map ? Map<String, Object?>.from(raw) : const {};
  static List<Map<String, Object?>> _list(Object? raw) => raw is List
      ? raw
            .whereType<Map>()
            .map((value) => Map<String, Object?>.from(value))
            .toList()
      : const [];
}
