import 'package:flutter_test/flutter_test.dart';
import 'package:quality_line_erp/core/security/security.dart';
import 'package:quality_line_erp/features/settings/access/models/permission_codes.dart';

void main() {
  test('R95 permission keys are generated by one canonical contract', () {
    expect(
      PermissionContract.action('sales', 'order.approve'),
      'sales.order.approve',
    );
    expect(
      PermissionContract.actionRestriction('sales'),
      'sales.actions.restrict',
    );
    expect(
      PermissionContract.recordScopeOwn('sales'),
      'sales.records.own',
    );
    expect(
      PermissionContract.recordScopeAll('sales'),
      'sales.records.all',
    );
    expect(
      PermissionContract.fieldView('cars', 'purchasePrice'),
      'cars.fields.purchasePrice.view',
    );
    expect(
      PermissionContract.fieldEdit('cars', 'purchasePrice'),
      'cars.fields.purchasePrice.edit',
    );

    expect(PermissionCodes.view('sales'), 'sales.view');
    expect(
      PermissionCodes.action('sales', 'invoice.reverse'),
      'sales.invoice.reverse',
    );
    expect(PermissionCodes.recordsOwn('sales'), 'sales.records.own');

    expect(
      () => PermissionContract.action('sales.order', 'approve'),
      throwsArgumentError,
    );
    expect(
      () => PermissionContract.fieldView('cars', 'purchase price'),
      throwsArgumentError,
    );
  });

  test('granular action restrictions preserve the migration boundary', () {
    const legacyOnly = {'sales.approve'};
    expect(
      PermissionContract.canPerformAction(
        legacyOnly,
        resource: 'sales',
        actionName: 'order.approve',
        legacyPermission: 'sales.approve',
      ),
      isTrue,
    );

    const restrictedWithoutAction = {
      'sales.approve',
      'sales.actions.restrict',
    };
    expect(
      PermissionContract.canPerformAction(
        restrictedWithoutAction,
        resource: 'sales',
        actionName: 'order.approve',
        legacyPermission: 'sales.approve',
      ),
      isFalse,
    );

    const restrictedWithAction = {
      'sales.approve',
      'sales.actions.restrict',
      'sales.order.approve',
    };
    expect(
      PermissionContract.canPerformAction(
        restrictedWithAction,
        resource: 'sales',
        actionName: 'order.approve',
        legacyPermission: 'sales.approve',
      ),
      isTrue,
    );
  });

  test('record scope precedence matches PostgreSQL R84 compatibility', () {
    expect(
      PermissionContract.resolveRecordScope(const <String>{}, 'sales'),
      RecordScopeMode.legacyAll,
    );
    expect(
      PermissionContract.resolveRecordScope(
        const {'sales.records.own'},
        'sales',
      ),
      RecordScopeMode.own,
    );
    expect(
      PermissionContract.resolveRecordScope(
        const {'sales.records.own', 'sales.records.all'},
        'sales',
      ),
      RecordScopeMode.all,
    );

    const ownSubject = AccessSubject(
      userId: 'u-1',
      roleIds: {'sales'},
      permissionCodes: {'sales.records.own'},
      tenantId: 'tenant-a',
      companyId: 'company-a',
    );
    const ownRecord = AccessResource(
      type: 'sales_order',
      id: 'so-1',
      ownerUserId: 'u-1',
      tenantId: 'tenant-a',
      companyId: 'company-a',
    );
    const otherRecord = AccessResource(
      type: 'sales_order',
      id: 'so-2',
      ownerUserId: 'u-2',
      tenantId: 'tenant-a',
      companyId: 'company-a',
    );

    expect(
      RecordRules.permissionScoped(
        const AccessRequest(
          subject: ownSubject,
          resource: ownRecord,
          operation: AccessOperation.read,
        ),
        module: 'sales',
      ),
      isTrue,
    );
    expect(
      RecordRules.permissionScoped(
        const AccessRequest(
          subject: ownSubject,
          resource: otherRecord,
          operation: AccessOperation.read,
        ),
        module: 'sales',
      ),
      isFalse,
    );
  });

  test('enterprise workflow operations are first-class policy operations', () {
    const subject = AccessSubject(
      userId: 'accountant-1',
      roleIds: {'accounting'},
      permissionCodes: {'accounting.reverse'},
      companyId: 'company-a',
    );
    const journal = AccessResource(
      type: 'journal_entry',
      id: 'je-1',
      companyId: 'company-a',
    );
    final engine = AccessPolicyEngine(
      policies: const [
        AccessPolicy(
          id: 'journal-reverse',
          resourceType: 'journal_entry',
          operations: {AccessOperation.reverse},
          effect: PolicyEffect.allow,
          requiredPermissions: {'accounting.reverse'},
          condition: RecordRules.sameCompany,
        ),
      ],
    );

    final decision = engine.evaluate(
      const AccessRequest(
        subject: subject,
        resource: journal,
        operation: AccessOperation.reverse,
      ),
    );
    expect(decision.allowed, isTrue);
    expect(decision.matchedPolicyIds, contains('journal-reverse'));

    expect(
      AccessOperation.values,
      containsAll(const [
        AccessOperation.save,
        AccessOperation.edit,
        AccessOperation.cancel,
        AccessOperation.reverse,
        AccessOperation.print,
        AccessOperation.openDetails,
        AccessOperation.assign,
        AccessOperation.transfer,
        AccessOperation.post,
        AccessOperation.reopen,
      ]),
    );
  });
}
