import 'permission_model.dart';

class FieldPermissionDefinition {
  const FieldPermissionDefinition(this.key, this.label);

  final String key;
  final String label;
}

class FieldPermissionResourceDefinition {
  const FieldPermissionResourceDefinition({
    required this.key,
    required this.module,
    required this.label,
    required this.fields,
  });

  final String key;
  final String module;
  final String label;
  final List<FieldPermissionDefinition> fields;
}

/// Granular field-level permission catalog.
///
/// Existing installations remain backwards compatible: field restrictions are
/// only enforced for a resource after `<resource>.fields.restrict` is granted
/// to the user/role. Once enabled, every protected field becomes default-deny
/// and must be explicitly granted `.view` and/or `.edit`.
abstract final class FieldPermissionCatalog {
  static const List<FieldPermissionResourceDefinition> resources = [
    FieldPermissionResourceDefinition(
      key: 'users',
      module: 'المستخدمون • الحقول',
      label: 'المستخدمين',
      fields: [
        FieldPermissionDefinition('fullName', 'الاسم الكامل'),
        FieldPermissionDefinition('username', 'اسم المستخدم'),
        FieldPermissionDefinition('email', 'البريد الإلكتروني'),
        FieldPermissionDefinition('phone', 'رقم الهاتف'),
        FieldPermissionDefinition('jobTitle', 'الدرجة الوظيفية'),
        FieldPermissionDefinition('roleId', 'الدور'),
        FieldPermissionDefinition('isActive', 'حالة المستخدم'),
        FieldPermissionDefinition('avatar', 'الصورة الشخصية'),
        FieldPermissionDefinition('password', 'كلمة المرور'),
        FieldPermissionDefinition('customPermissions', 'الصلاحيات المخصصة'),
        FieldPermissionDefinition('auditMetadata', 'بيانات التدقيق للمستخدم'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'dashboard',
      module: 'لوحة التحكم • الحقول',
      label: 'لوحة التحكم',
      fields: [
        FieldPermissionDefinition('totalCars', 'إجمالي السيارات'),
        FieldPermissionDefinition('availableCars', 'السيارات المتوفرة'),
        FieldPermissionDefinition('reservedCars', 'السيارات قيد البيع'),
        FieldPermissionDefinition('soldCars', 'السيارات المباعة'),
        FieldPermissionDefinition('totalCustomers', 'إجمالي العملاء'),
        FieldPermissionDefinition('totalSuppliers', 'إجمالي الموردين'),
        FieldPermissionDefinition('totalSales', 'إجمالي المبيعات'),
        FieldPermissionDefinition('todaySales', 'مبيعات اليوم'),
        FieldPermissionDefinition('totalPurchases', 'إجمالي المشتريات'),
        FieldPermissionDefinition('totalExpenses', 'إجمالي المصروفات'),
        FieldPermissionDefinition('netProfit', 'صافي الربح'),
        FieldPermissionDefinition('cashBalanceUsd', 'رصيد الصناديق USD'),
        FieldPermissionDefinition('cashBalanceIqd', 'رصيد الصناديق IQD'),
        FieldPermissionDefinition('inventoryValue', 'قيمة المخزون'),
        FieldPermissionDefinition('totalReceivables', 'الذمم المدينة'),
        FieldPermissionDefinition('totalPayables', 'الذمم الدائنة'),
        FieldPermissionDefinition('pendingPurchaseCars', 'السيارات قيد الشراء'),
        FieldPermissionDefinition('lowStockItems', 'المواد منخفضة المخزون'),
        FieldPermissionDefinition('carsWithoutWarehouse', 'السيارات بلا مخزن'),
        FieldPermissionDefinition('activeReservations', 'الحجوزات النشطة'),
        FieldPermissionDefinition('overdueInstallments', 'الأقساط المتأخرة'),
        FieldPermissionDefinition('dueSoonInstallments', 'الأقساط القريبة'),
        FieldPermissionDefinition(
          'outstandingInstallments',
          'إجمالي الأقساط المتبقية',
        ),
        FieldPermissionDefinition('salesTrend', 'اتجاه المبيعات'),
        FieldPermissionDefinition('recentActivities', 'آخر النشاطات'),
        FieldPermissionDefinition('upcomingInstallments', 'الأقساط القادمة'),
        FieldPermissionDefinition(
          'pendingSyncOperations',
          'عمليات المزامنة المعلقة',
        ),
        FieldPermissionDefinition('generatedAt', 'وقت آخر تحديث'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'cars',
      module: 'السيارات • الحقول',
      label: 'السيارات',
      fields: [
        FieldPermissionDefinition('vehicleType', 'نوع السيارة'),
        FieldPermissionDefinition('brand', 'الماركة'),
        FieldPermissionDefinition('model', 'الموديل'),
        FieldPermissionDefinition('year', 'سنة الصنع'),
        FieldPermissionDefinition('color', 'اللون'),
        FieldPermissionDefinition('chassis', 'رقم الشاصي'),
        FieldPermissionDefinition('engineNumber', 'رقم المحرك'),
        FieldPermissionDefinition('plateNumber', 'رقم اللوحة'),
        FieldPermissionDefinition('carNumber', 'رقم السيارة'),
        FieldPermissionDefinition('purchasePrice', 'سعر الشراء'),
        FieldPermissionDefinition('maintenanceCost', 'كلفة الصيانة المتراكمة'),
        FieldPermissionDefinition('salePrice', 'سعر البيع'),
        FieldPermissionDefinition('margin', 'الهامش/الربح'),
        FieldPermissionDefinition('maintenanceHistory', 'سجل الصيانة'),
        FieldPermissionDefinition('currency', 'عملة التعريف'),
        FieldPermissionDefinition('status', 'حالة السيارة'),
        FieldPermissionDefinition('warehouseId', 'المخزن'),
        FieldPermissionDefinition('supplierId', 'المورد'),
        FieldPermissionDefinition('purchaseDate', 'تاريخ الشراء'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('images', 'الصور'),
        FieldPermissionDefinition('inventoryAssetAccountId', 'حساب المخزون'),
        FieldPermissionDefinition(
          'salesCostExpenseAccountId',
          'حساب كلفة المبيعات',
        ),
        FieldPermissionDefinition(
          'salesRevenueIqdAccountId',
          'حساب إيراد الدينار',
        ),
        FieldPermissionDefinition(
          'salesRevenueUsdAccountId',
          'حساب إيراد الدولار',
        ),
        FieldPermissionDefinition(
          'auditMetadata',
          'بيانات إنشاء وتحديث السيارة',
        ),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'inventory',
      module: 'المخزون • الحقول',
      label: 'المنتجات والخدمات',
      fields: [
        FieldPermissionDefinition('name', 'الاسم العربي'),
        FieldPermissionDefinition('nameEn', 'الاسم الإنجليزي'),
        FieldPermissionDefinition('description', 'الوصف'),
        FieldPermissionDefinition('code', 'الرمز'),
        FieldPermissionDefinition('sku', 'SKU'),
        FieldPermissionDefinition('barcode', 'الباركود'),
        FieldPermissionDefinition('serialNumber', 'الرقم التسلسلي'),
        FieldPermissionDefinition('category', 'التصنيف'),
        FieldPermissionDefinition('groupId', 'مجموعة المخزون'),
        FieldPermissionDefinition('warehouseId', 'المخزن'),
        FieldPermissionDefinition('unit', 'وحدة القياس'),
        FieldPermissionDefinition('quantity', 'الكمية'),
        FieldPermissionDefinition('purchasePrice', 'سعر الشراء'),
        FieldPermissionDefinition('landedCost', 'الكلفة الواصلة'),
        FieldPermissionDefinition('unitCost', 'كلفة الوحدة'),
        FieldPermissionDefinition('salePrice', 'سعر البيع'),
        FieldPermissionDefinition('currency', 'عملة التعريف'),
        FieldPermissionDefinition('taxRate', 'نسبة الضريبة'),
        FieldPermissionDefinition('minQuantity', 'الحد الأدنى'),
        FieldPermissionDefinition('expectedIncoming', 'الوارد المتوقع'),
        FieldPermissionDefinition('expectedOutgoing', 'الصادر المتوقع'),
        FieldPermissionDefinition('date', 'تاريخ التعريف'),
        FieldPermissionDefinition('image', 'الصورة'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('isActive', 'حالة النشاط'),
        FieldPermissionDefinition('itemType', 'نوع المادة/الخدمة'),
        FieldPermissionDefinition(
          'transferItem',
          'المادة/السيارة في سند النقل',
        ),
        FieldPermissionDefinition('sourceWarehouseId', 'مخزن المصدر'),
        FieldPermissionDefinition('destinationWarehouseId', 'مخزن الوجهة'),
        FieldPermissionDefinition('transferQuantity', 'كمية النقل'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('transferNotes', 'ملاحظات النقل'),
        FieldPermissionDefinition('movementNumber', 'رقم حركة المخزون'),
        FieldPermissionDefinition('movementType', 'نوع حركة المخزون'),
        FieldPermissionDefinition('movementCost', 'كلفة حركة المخزون'),
        FieldPermissionDefinition('movementReference', 'مرجع حركة المخزون'),
        FieldPermissionDefinition(
          'auditMetadata',
          'بيانات تدقيق حركة/تعريف المخزون',
        ),
        FieldPermissionDefinition('inventoryAssetAccountId', 'حساب المخزون'),
        FieldPermissionDefinition(
          'salesCostExpenseAccountId',
          'حساب كلفة المبيعات',
        ),
        FieldPermissionDefinition(
          'salesRevenueIqdAccountId',
          'حساب إيراد الدينار',
        ),
        FieldPermissionDefinition(
          'salesRevenueUsdAccountId',
          'حساب إيراد الدولار',
        ),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'warehouses',
      module: 'المخازن • الحقول',
      label: 'المخازن',
      fields: [
        FieldPermissionDefinition('code', 'رمز المخزن'),
        FieldPermissionDefinition('name', 'اسم المخزن'),
        FieldPermissionDefinition('branchId', 'الفرع'),
        FieldPermissionDefinition('address', 'العنوان'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('isActive', 'حالة المخزن'),
        FieldPermissionDefinition('warehouseType', 'نوع المخزن'),
        FieldPermissionDefinition('inventoryAccountId', 'حساب المخزون'),
        FieldPermissionDefinition('scrapExpenseAccountId', 'حساب كلفة التالف'),
        FieldPermissionDefinition(
          'scrapExpenseIqdAccountId',
          'حساب كلفة التالف IQD',
        ),
        FieldPermissionDefinition(
          'scrapExpenseUsdAccountId',
          'حساب كلفة التالف USD',
        ),
        FieldPermissionDefinition('createdAt', 'تاريخ إنشاء المخزن'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'customers',
      module: 'العملاء • الحقول',
      label: 'العملاء',
      fields: [
        FieldPermissionDefinition('name', 'اسم العميل'),
        FieldPermissionDefinition('phone', 'الهاتف'),
        FieldPermissionDefinition('address', 'العنوان'),
        FieldPermissionDefinition('nationalId', 'الهوية/الرقم الوطني'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('photo', 'الصورة'),
        FieldPermissionDefinition('createdAt', 'تاريخ إنشاء العميل'),
        FieldPermissionDefinition('accountIqd', 'حساب العميل بالدينار'),
        FieldPermissionDefinition('accountUsd', 'حساب العميل بالدولار'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'suppliers',
      module: 'الموردون • الحقول',
      label: 'الموردين',
      fields: [
        FieldPermissionDefinition('name', 'اسم المورد'),
        FieldPermissionDefinition('phone', 'الهاتف'),
        FieldPermissionDefinition('alternativePhone', 'الهاتف البديل'),
        FieldPermissionDefinition('address', 'العنوان'),
        FieldPermissionDefinition('companyName', 'اسم الشركة'),
        FieldPermissionDefinition('taxNumber', 'الرقم الضريبي'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('openingBalance', 'الرصيد الافتتاحي'),
        FieldPermissionDefinition('currency', 'عملة الرصيد'),
        FieldPermissionDefinition('isActive', 'حالة المورد'),
        FieldPermissionDefinition('photo', 'الصورة'),
        FieldPermissionDefinition('createdAt', 'تاريخ إنشاء المورد'),
        FieldPermissionDefinition('updatedAt', 'تاريخ تحديث المورد'),
        FieldPermissionDefinition('accountIqd', 'حساب المورد بالدينار'),
        FieldPermissionDefinition('accountUsd', 'حساب المورد بالدولار'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'sales',
      module: 'المبيعات • الحقول',
      label: 'المبيعات',
      fields: [
        FieldPermissionDefinition('orderNumber', 'رقم أمر البيع'),
        FieldPermissionDefinition('customerId', 'العميل'),
        FieldPermissionDefinition('customerName', 'اسم العميل'),
        FieldPermissionDefinition('carId', 'السيارة'),
        FieldPermissionDefinition('opportunityId', 'الفرصة التجارية'),
        FieldPermissionDefinition('currencyCode', 'عملة أمر البيع'),
        FieldPermissionDefinition('exchangeRate', 'معامل التحويل'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('items', 'بنود أمر البيع'),
        FieldPermissionDefinition('itemWarehouse', 'مخزن البند'),
        FieldPermissionDefinition('itemQuantity', 'كمية البند'),
        FieldPermissionDefinition('itemPrice', 'سعر البند'),
        FieldPermissionDefinition('subtotal', 'الإجمالي قبل الخصم'),
        FieldPermissionDefinition('discount', 'الخصم'),
        FieldPermissionDefinition('total', 'إجمالي أمر البيع'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('status', 'حالة الأمر'),
        FieldPermissionDefinition('delivery', 'التجهيز المخزني'),
        FieldPermissionDefinition('invoice', 'الفاتورة'),
        FieldPermissionDefinition('payments', 'الدفعات المالية'),
        FieldPermissionDefinition('accounting', 'القيود المحاسبية'),
        FieldPermissionDefinition('createdAt', 'تاريخ الإنشاء'),
        FieldPermissionDefinition('updatedAt', 'تاريخ آخر تحديث'),
        FieldPermissionDefinition('saleType', 'نوع البيع'),
        FieldPermissionDefinition('previousSaleId', 'البيع السابق المرتبط'),
        FieldPermissionDefinition('createdBy', 'منشئ عملية البيع'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'purchases',
      module: 'المشتريات • الحقول',
      label: 'المشتريات',
      fields: [
        FieldPermissionDefinition('orderNumber', 'رقم أمر الشراء'),
        FieldPermissionDefinition('supplierId', 'المورد'),
        FieldPermissionDefinition('supplierName', 'اسم المورد'),
        FieldPermissionDefinition('currencyCode', 'عملة أمر الشراء'),
        FieldPermissionDefinition('exchangeRate', 'معامل التحويل'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('items', 'بنود أمر الشراء'),
        FieldPermissionDefinition('itemWarehouse', 'مخزن البند'),
        FieldPermissionDefinition('itemQuantity', 'كمية البند'),
        FieldPermissionDefinition('itemCost', 'كلفة البند'),
        FieldPermissionDefinition('subtotal', 'الإجمالي قبل الخصم'),
        FieldPermissionDefinition('discount', 'الخصم'),
        FieldPermissionDefinition('total', 'إجمالي أمر الشراء'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('status', 'حالة الأمر'),
        FieldPermissionDefinition('receipt', 'الاستلام المخزني'),
        FieldPermissionDefinition('invoice', 'الفاتورة'),
        FieldPermissionDefinition('payments', 'الدفعات المالية'),
        FieldPermissionDefinition('accounting', 'القيود المحاسبية'),
        FieldPermissionDefinition('createdAt', 'تاريخ الإنشاء'),
        FieldPermissionDefinition('updatedAt', 'تاريخ آخر تحديث'),
        FieldPermissionDefinition('createdBy', 'منشئ عملية الشراء'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'maintenance',
      module: 'الصيانة • الحقول',
      label: 'الصيانة',
      fields: [
        FieldPermissionDefinition('orderNumber', 'رقم أمر الصيانة'),
        FieldPermissionDefinition('carId', 'السيارة'),
        FieldPermissionDefinition('carName', 'اسم/وصف السيارة'),
        FieldPermissionDefinition('customerId', 'العميل'),
        FieldPermissionDefinition('customerName', 'اسم العميل'),
        FieldPermissionDefinition('warehouseId', 'المخزن'),
        FieldPermissionDefinition('currencyCode', 'العملة'),
        FieldPermissionDefinition('exchangeRate', 'معامل التحويل'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('pricingType', 'نوع الصيانة'),
        FieldPermissionDefinition('laborCost', 'كلفة العمل'),
        FieldPermissionDefinition('partsCost', 'كلفة المواد'),
        FieldPermissionDefinition('totalCost', 'إجمالي الكلفة'),
        FieldPermissionDefinition('items', 'مواد وخدمات الصيانة'),
        FieldPermissionDefinition('itemWarehouse', 'مخزن السحب'),
        FieldPermissionDefinition('itemQuantity', 'كمية البند'),
        FieldPermissionDefinition('itemPrice', 'سعر البند'),
        FieldPermissionDefinition('salePrice', 'سعر الفاتورة'),
        FieldPermissionDefinition('profit', 'الربح'),
        FieldPermissionDefinition('carCostAdded', 'الكلفة المضافة للسيارة'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('status', 'الحالة'),
        FieldPermissionDefinition('workflowStage', 'مرحلة سير العمل'),
        FieldPermissionDefinition('stockIssue', 'التجهيز المخزني'),
        FieldPermissionDefinition('stockIssueNumber', 'رقم التجهيز المخزني'),
        FieldPermissionDefinition('invoice', 'الفاتورة'),
        FieldPermissionDefinition('invoiceNumber', 'رقم الفاتورة'),
        FieldPermissionDefinition('payments', 'الدفعات المالية'),
        FieldPermissionDefinition('accounting', 'القيود المحاسبية'),
        FieldPermissionDefinition('isSoldCar', 'حالة السيارة المباعة'),
        FieldPermissionDefinition('cancelReason', 'سبب الإلغاء'),
        FieldPermissionDefinition(
          'maintenanceExpenseAccountId',
          'حساب مصروف الصيانة',
        ),
        FieldPermissionDefinition('createdBy', 'منشئ أمر الصيانة'),
        FieldPermissionDefinition('materialCost', 'كلفة المواد الفعلية'),
        FieldPermissionDefinition('margin', 'هامش الصيانة'),
        FieldPermissionDefinition('maintenanceSchedule', 'جداول الصيانة'),
        FieldPermissionDefinition(
          'maintenanceHistoryDetails',
          'التفاصيل المخصصة لسجل الصيانة',
        ),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'opportunities',
      module: 'الفرص التجارية • الحقول',
      label: 'الفرص التجارية',
      fields: [
        FieldPermissionDefinition('opportunityNumber', 'رقم الفرصة'),
        FieldPermissionDefinition('stage', 'مرحلة الفرصة'),
        FieldPermissionDefinition('probability', 'احتمالية الفرصة'),
        FieldPermissionDefinition('currency', 'عملة الفرصة'),
        FieldPermissionDefinition('description', 'وصف الفرصة'),
        FieldPermissionDefinition('expectedCloseDate', 'تاريخ الإغلاق المتوقع'),
        FieldPermissionDefinition('winLossReason', 'سبب الفوز أو الخسارة'),
        FieldPermissionDefinition('customerId', 'العميل'),
        FieldPermissionDefinition('customerName', 'اسم العميل'),
        FieldPermissionDefinition('customerPhone', 'هاتف العميل'),
        FieldPermissionDefinition('assignedUserId', 'المستخدم المسؤول'),
        FieldPermissionDefinition('assignedUserName', 'اسم المستخدم المسؤول'),
        FieldPermissionDefinition('createdBy', 'منشئ الفرصة'),
        FieldPermissionDefinition('title', 'عنوان الفرصة'),
        FieldPermissionDefinition('value', 'القيمة'),
        FieldPermissionDefinition('status', 'حالة الفرصة'),
        FieldPermissionDefinition('car', 'السيارة المرتبطة'),
        FieldPermissionDefinition('source', 'المصدر'),
        FieldPermissionDefinition('followUpDate', 'تاريخ المتابعة'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('linkedSale', 'البيع المرتبط'),
        FieldPermissionDefinition('createdAt', 'تاريخ الإنشاء'),
        FieldPermissionDefinition('closedAt', 'تاريخ الإغلاق'),
        FieldPermissionDefinition('updatedAt', 'آخر تحديث'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'installments',
      module: 'الأقساط • الحقول',
      label: 'الأقساط والدفعات',
      fields: [
        FieldPermissionDefinition('saleId', 'فاتورة/عملية البيع المرتبطة'),
        FieldPermissionDefinition('installmentNo', 'رقم القسط'),
        FieldPermissionDefinition('dueDate', 'تاريخ الاستحقاق'),
        FieldPermissionDefinition('amount', 'قيمة القسط'),
        FieldPermissionDefinition('paidAmount', 'المبلغ المدفوع'),
        FieldPermissionDefinition('remainingAmount', 'المبلغ المتبقي'),
        FieldPermissionDefinition('status', 'حالة القسط'),
        FieldPermissionDefinition('paymentDate', 'تاريخ الدفع'),
        FieldPermissionDefinition('notes', 'ملاحظات القسط'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'accounting',
      module: 'المحاسبة • الحقول',
      label: 'المحاسبة',
      fields: [
        FieldPermissionDefinition('accountCode', 'رمز الحساب'),
        FieldPermissionDefinition('accountName', 'اسم الحساب'),
        FieldPermissionDefinition('accountType', 'نوع الحساب'),
        FieldPermissionDefinition('parentAccount', 'الحساب الأب'),
        FieldPermissionDefinition('currency', 'عملة الحساب/القيد'),
        FieldPermissionDefinition('openingBalance', 'الرصيد الافتتاحي'),
        FieldPermissionDefinition('isActive', 'حالة الحساب'),
        FieldPermissionDefinition('entryNumber', 'رقم القيد'),
        FieldPermissionDefinition('entryDate', 'تاريخ ووقت القيد'),
        FieldPermissionDefinition('description', 'البيان'),
        FieldPermissionDefinition('journalLines', 'سطور القيد'),
        FieldPermissionDefinition('debit', 'المدين'),
        FieldPermissionDefinition('credit', 'الدائن'),
        FieldPermissionDefinition('reference', 'مرجع القيد'),
        FieldPermissionDefinition('trialBalance', 'ميزان المراجعة'),
        FieldPermissionDefinition('generalLedger', 'دفتر الأستاذ'),
        FieldPermissionDefinition('cashFlow', 'التدفق النقدي'),
        FieldPermissionDefinition('balances', 'الأرصدة'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'cashbox',
      module: 'الصندوق • الحقول',
      label: 'الصناديق والحركات المالية',
      fields: [
        FieldPermissionDefinition('name', 'اسم الصندوق'),
        FieldPermissionDefinition('type', 'نوع الصندوق'),
        FieldPermissionDefinition('currency', 'عملة الصندوق'),
        FieldPermissionDefinition('ledgerAccount', 'حساب دفتر الأستاذ'),
        FieldPermissionDefinition('linkedCashAccount', 'الصندوق المرتبط'),
        FieldPermissionDefinition('cashAccount', 'الصندوق المستخدم في السند'),
        FieldPermissionDefinition('openingBalance', 'الرصيد الافتتاحي'),
        FieldPermissionDefinition('isActive', 'حالة الصندوق'),
        FieldPermissionDefinition('transactionType', 'نوع الحركة'),
        FieldPermissionDefinition('documentNumber', 'رقم السند'),
        FieldPermissionDefinition('amount', 'المبلغ'),
        FieldPermissionDefinition('counterAccount', 'الحساب المقابل'),
        FieldPermissionDefinition('purpose', 'الغرض/التصنيف'),
        FieldPermissionDefinition('partyType', 'نوع الجهة'),
        FieldPermissionDefinition('partyName', 'اسم الجهة'),
        FieldPermissionDefinition('partyId', 'مرجع الجهة'),
        FieldPermissionDefinition('paymentMethod', 'طريقة الدفع'),
        FieldPermissionDefinition('reference', 'مرجع الحركة'),
        FieldPermissionDefinition('journalEntryId', 'مرجع القيد المحاسبي'),
        FieldPermissionDefinition('performedBy', 'منفذ حركة الصندوق'),
        FieldPermissionDefinition('transactionStatus', 'حالة الحركة'),
        FieldPermissionDefinition(
          'auditMetadata',
          'بيانات إنشاء وتحديث الحركة',
        ),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('exchangeRate', 'معامل التحويل'),
        FieldPermissionDefinition('transferFrom', 'صندوق التحويل المصدر'),
        FieldPermissionDefinition('transferTo', 'صندوق التحويل الوجهة'),
        FieldPermissionDefinition('balance', 'الرصيد الحالي للصندوق'),
        FieldPermissionDefinition('ledgerBalance', 'رصيد دفتر الأستاذ للصندوق'),
        FieldPermissionDefinition('reconciliationDifference', 'فرق المطابقة'),
        FieldPermissionDefinition(
          'reconciliation',
          'مطابقة الصندوق مع الأستاذ',
        ),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'expenses',
      module: 'المصروفات • الحقول',
      label: 'المصروفات',
      fields: [
        FieldPermissionDefinition('name', 'اسم المصروف'),
        FieldPermissionDefinition('amount', 'المبلغ'),
        FieldPermissionDefinition('currency', 'العملة'),
        FieldPermissionDefinition('cashAccount', 'الصندوق'),
        FieldPermissionDefinition('expenseAccount', 'حساب المصروف'),
        FieldPermissionDefinition('category', 'التصنيف'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('postingStatus', 'حالة الترحيل'),
        FieldPermissionDefinition('approvalStatus', 'حالة الاعتماد'),
        FieldPermissionDefinition('branchId', 'الفرع'),
        FieldPermissionDefinition('exchangeRate', 'معامل التحويل'),
        FieldPermissionDefinition('convertedAmounts', 'القيم المحولة للعملات'),
        FieldPermissionDefinition('journalEntryId', 'مرجع القيد المحاسبي'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'fixed_assets',
      module: 'الأصول الثابتة • الحقول',
      label: 'الأصول الثابتة',
      fields: [
        FieldPermissionDefinition('assetCode', 'رمز الأصل'),
        FieldPermissionDefinition('name', 'اسم الأصل'),
        FieldPermissionDefinition('acquisitionCost', 'كلفة الاقتناء'),
        FieldPermissionDefinition('salvageValue', 'قيمة الخردة'),
        FieldPermissionDefinition('usefulLifeMonths', 'العمر بالأشهر'),
        FieldPermissionDefinition('currency', 'العملة'),
        FieldPermissionDefinition('depreciationMethod', 'طريقة الإهلاك'),
        FieldPermissionDefinition('decliningRate', 'معدل الإهلاك المتناقص'),
        FieldPermissionDefinition('assetAccount', 'حساب الأصل'),
        FieldPermissionDefinition(
          'accumulatedDepreciationAccount',
          'حساب مجمع الإهلاك',
        ),
        FieldPermissionDefinition(
          'depreciationExpenseAccount',
          'حساب مصروف الإهلاك',
        ),
        FieldPermissionDefinition('operationalDate', 'التاريخ والوقت التشغيلي'),
        FieldPermissionDefinition('accumulatedDepreciation', 'مجمع الإهلاك'),
        FieldPermissionDefinition('bookValue', 'القيمة الدفترية'),
        FieldPermissionDefinition(
          'depreciationPostingDate',
          'تاريخ ترحيل الإهلاك',
        ),
        FieldPermissionDefinition('isActive', 'حالة الأصل'),
        FieldPermissionDefinition('notes', 'الملاحظات'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'reports',
      module: 'التقارير • الحقول',
      label: 'التقارير',
      fields: [
        FieldPermissionDefinition('dateRange', 'الفترة الزمنية'),
        FieldPermissionDefinition('currencyFilter', 'فلتر العملة'),
        FieldPermissionDefinition('cashboxFilter', 'فلتر الصندوق النقدي'),
        FieldPermissionDefinition('totalDebit', 'إجمالي المدين'),
        FieldPermissionDefinition('totalCredit', 'إجمالي الدائن'),
        FieldPermissionDefinition('cashIn', 'التدفقات الداخلة'),
        FieldPermissionDefinition('cashOut', 'التدفقات الخارجة'),
        FieldPermissionDefinition('netCashFlow', 'صافي التدفق النقدي'),
        FieldPermissionDefinition('journalLedger', 'دفتر اليومية/الأستاذ'),
        FieldPermissionDefinition('trialBalance', 'ميزان المراجعة'),
        FieldPermissionDefinition('inventoryValue', 'قيمة المخزون'),
        FieldPermissionDefinition('exportPdf', 'تصدير PDF'),
        FieldPermissionDefinition('summaryCards', 'بطاقات الملخص العام'),
        FieldPermissionDefinition('monthlyTrend', 'الاتجاه الشهري'),
        FieldPermissionDefinition(
          'contextualDetails',
          'تفاصيل التقارير السياقية',
        ),
        FieldPermissionDefinition('auditDetails', 'تفاصيل سجل التدقيق'),
        FieldPermissionDefinition('netProfit', 'صافي الربح'),
        FieldPermissionDefinition('cashBalances', 'أرصدة الصناديق'),
        FieldPermissionDefinition(
          'receivablesPayables',
          'الذمم المدينة والدائنة',
        ),
        FieldPermissionDefinition('exportExcel', 'تصدير Excel'),
      ],
    ),
    FieldPermissionResourceDefinition(
      key: 'settings',
      module: 'الإعدادات • الحقول',
      label: 'الإعدادات',
      fields: [
        FieldPermissionDefinition('companyProfile', 'بيانات الشركة'),
        FieldPermissionDefinition('branches', 'الفروع'),
        FieldPermissionDefinition('currencies', 'العملات'),
        FieldPermissionDefinition('financialDefaults', 'الإعدادات المالية'),
        FieldPermissionDefinition('theme', 'المظهر والثيم'),
        FieldPermissionDefinition('language', 'اللغة'),
        FieldPermissionDefinition('backup', 'النسخ الاحتياطي'),
        FieldPermissionDefinition('restore', 'الاستعادة'),
        FieldPermissionDefinition('auditLog', 'سجل التدقيق'),
        FieldPermissionDefinition('systemMonitor', 'مراقبة النظام'),
        FieldPermissionDefinition('systemHealth', 'حالة الاتصال والصحة'),
        FieldPermissionDefinition('systemMetrics', 'مؤشرات النظام'),
        FieldPermissionDefinition('systemSyncDetails', 'تفاصيل المزامنة'),
        FieldPermissionDefinition('productionReadiness', 'جاهزية الإنتاج'),
        FieldPermissionDefinition(
          'retryFailedJobs',
          'إعادة محاولة العمليات الفاشلة',
        ),
        FieldPermissionDefinition('recycleBin', 'سلة المهملات'),
        FieldPermissionDefinition('operationalPeriods', 'الفترات التشغيلية'),
      ],
    ),
  ];

  static String restrictCode(String resource) => '$resource.fields.restrict';
  static String viewCode(String resource, String field) =>
      '$resource.fields.$field.view';
  static String editCode(String resource, String field) =>
      '$resource.fields.$field.edit';

  static FieldPermissionResourceDefinition? resource(String key) {
    for (final item in resources) {
      if (item.key == key) return item;
    }
    return null;
  }

  static bool isKnownField(String resourceKey, String fieldKey) {
    final item = resource(resourceKey);
    if (item == null) return false;
    return item.fields.any((field) => field.key == fieldKey);
  }

  static final List<PermissionModel> all = [
    for (final resource in resources) ...[
      PermissionModel(
        id: 'catalog-${resource.key}-fields-restrict',
        code: restrictCode(resource.key),
        name: 'تفعيل تقييد حقول ${resource.label}',
        module: resource.module,
        description:
            'عند تفعيلها تصبح حقول ${resource.label} محجوبة افتراضياً، ويجب منح عرض/تعديل لكل حقل مطلوب.',
      ),
      for (final field in resource.fields) ...[
        PermissionModel(
          id: 'catalog-${resource.key}-${field.key}-view',
          code: viewCode(resource.key, field.key),
          name: 'عرض • ${field.label}',
          module: resource.module,
          description: 'السماح بعرض حقل ${field.label}.',
        ),
        PermissionModel(
          id: 'catalog-${resource.key}-${field.key}-edit',
          code: editCode(resource.key, field.key),
          name: 'تعديل • ${field.label}',
          module: resource.module,
          description: 'السماح بتعديل حقل ${field.label}.',
        ),
      ],
    ],
  ];
}
