from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
def t(p): return (ROOT/p).read_text(encoding='utf-8',errors='ignore')
checks={}
def need(n,v): checks[n]=bool(v)
car_repo=t('lib/features/inventory/cars/data/car_images_repository.dart')
car_ctl=t('lib/features/inventory/cars/controllers/car_images_controller.dart')
car_page=t('lib/features/inventory/cars/pages/cars_page.dart')
car_card=t('lib/features/inventory/cars/widgets/car_card.dart')
inv=t('lib/features/inventory/pages/inventory_page.dart')
maint=t('lib/features/maintenance/pages/add_maintenance_order_page.dart')
sales=t('lib/features/sales/workflow/repositories/sales_workflow_repository.dart')
opp=t('lib/features/customer_service/pages/customer_service_page.dart')
workflow_card=t('lib/core/widgets/commercial_workflow_order_card.dart')
maint_page=t('lib/features/maintenance/pages/maintenance_page.dart')
pdfweb=t('lib/core/exporting/pdf_print_service_web.dart')
version=t('web/version.json')
pkg=t('package.json')
mig=t('supabase/migrations/20260809213000_r43_performance_functional_closure.sql')
need('batch thumbnail RPC client', ('erp_r43_list_car_thumbnails' in car_repo or 'erp_r44_list_car_thumbnails' in car_repo) and 'getThumbnails' in car_repo)
need('batch thumbnail cache', 'loadThumbnails' in car_ctl)
need('cars prefetch thumbnails', '_loadCarsAndThumbnails' in car_page and 'loadThumbnails' in car_page)
need('no per-card image RPC trigger', 'loadImages(widget.carId)' not in car_card)
need('product detail Excel', 'Product Details' in inv and 'ExcelExportService().build' in inv and 'Performed by' in inv)
need('product detail PDF', 'PdfExportService().save' in inv)
need('maintenance labor-only allowed', 'Add at least one item or service' not in maint)
need('opportunity reconciliation after sales', 'erp_r43_reconcile_opportunity_sales_links' in sales)
need('R43 migration thumbnail function', 'erp_r43_list_car_thumbnails' in mig)
need('R43 migration reconciliation', 'erp_r43_reconcile_opportunity_sales_links' in mig)
need('opportunity export visible with customer service view', "customer_service.view" in opp and 'ExcelExportService().build(_opportunityExport(rows))' in opp and 'PdfExportService().save(_opportunityExport(rows))' in opp)
need('commercial metric alias resilience', '_first(const' in workflow_card and 'invoice_number' in workflow_card and 'payment_status' in workflow_card)
need('maintenance approval explicit', 'FilledButton.icon' in maint_page and "maintenance.approve" in maint_page)
need('web print visible-tab fallback', "html.window.open(url, '_blank')" in pdfweb and 'html.Blob' in pdfweb and 'AnchorElement' in pdfweb and '..download = safeFileName' in pdfweb)
need('R43 metadata', ('r43-performance-functional-closure-20260809' in version and '22.9.8-r43-performance-functional-closure' in version) or ('r49-' in version and '22.9.8-r49-' in version))
need('R43 default deploy safe gate', (('deploy_r43_production.ps1' in pkg and '20260809213000' in t('tool/deploy_r43_production.ps1')) or ('deploy_r49_production.ps1' in pkg and '20260810021000_r49_crm_business_reference_closure.sql' in t('tool/deploy_r49_production.ps1'))))
for n,v in checks.items(): print(('PASS' if v else 'FAIL'),n)
if not all(checks.values()): sys.exit(1)
print(f'PASS R43 performance/functional closure — {len(checks)} gates')
