begin;

-- R47 PRODUCTION RUNTIME DEPENDENCY CLOSURE
-- Repairs concrete production defects surfaced by Supabase db lint without
-- weakening R46 invoice-owned accounting boundaries.

-- Stable UUID helper required by V760 purchase FX settlement provisioning.
create or replace function public.erp_deterministic_uuid(p_seed text)
returns uuid
language sql immutable strict parallel safe
set search_path=public
as $$
  select (
    substr(md5(p_seed),1,8)||'-'||
    substr(md5(p_seed),9,4)||'-'||
    '5'||substr(md5(p_seed),14,3)||'-'||
    '8'||substr(md5(p_seed),18,3)||'-'||
    substr(md5(p_seed),21,12)
  )::uuid
$$;

-- Retire the historical transfer body that referenced a missing helper.
-- Legacy callers are routed through the current R22 canonical transfer engine.
create or replace function public.erp_transfer_cloud_cash(
  p_company_id uuid,p_from_cash_account_id text,p_to_cash_account_id text,
  p_source_amount numeric,p_target_amount numeric,p_exchange_rate numeric,
  p_transfer_date timestamptz,p_notes text default null
) returns void
language plpgsql security definer set search_path=public as $$
begin
  perform public.erp_r22_transfer_cloud_cash(
    p_company_id,p_from_cash_account_id,p_to_cash_account_id,
    p_source_amount,p_target_amount,p_exchange_rate,p_transfer_date,p_notes);
end
$$;

-- PostgreSQL has jsonb_array_length but no jsonb_object_length in this runtime.
-- Rebuild the V760 normalizer with an explicit jsonb_object_keys count.
create or replace function public.erp_v760_normalize_purchase_invoice_posting(
  p_company_id uuid,p_invoice_id uuid
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  d public.erp_commercial_workflow_documents%rowtype;
  v_currency text; v_total numeric; v_order_rate numeric; v_supplier text;
  v_supplier_account text; v_subtotal numeric; v_factor numeric:=1; v_effective timestamptz;
  r record; ac jsonb; v_cost_currency text; v_amount numeric; v_converted numeric;
  v_by_currency jsonb:='{}'::jsonb; v_invoice_lines jsonb:='[]'::jsonb;
  v_entry text; v_entries jsonb:='[]'::jsonb; v_settlement jsonb; v_settlement_id text;
  v_old_ids text[]:=array[]::text[]; x jsonb; k text; lines jsonb;
begin
  select * into d from public.erp_commercial_workflow_documents
   where company_id=p_company_id and id=p_invoice_id and module='purchases'
     and document_type='invoice' and not is_deleted for update;
  if not found then raise exception 'workflow_invoice_not_found'; end if;
  if d.status<>'approved' then raise exception 'workflow_invoice_not_approved'; end if;
  if public.erp_try_boolean(d.payload->>'v760NoCapitalizationNormalized','false') then
    return jsonb_build_object('ok',true,'alreadyNormalized',true);
  end if;

  v_currency:=upper(coalesce(d.payload->>'currency',''));
  v_total:=public.erp_try_numeric(d.payload->>'totalAmount',0);
  v_effective:=coalesce(d.effective_at,d.created_at,now());
  select supplier_id,subtotal,exchange_rate into v_supplier,v_subtotal,v_order_rate
    from public.erp_purchase_orders_cloud
   where company_id=p_company_id and id=d.parent_id and not is_deleted;
  if not found or v_currency not in ('IQD','USD') or v_total<=0 then
    raise exception 'purchase_invoice_header_invalid';
  end if;
  v_supplier_account:=public.erp_workflow_partner_account(
    p_company_id,'supplier',v_supplier,v_currency);
  v_factor:=case when coalesce(v_subtotal,0)>0 then v_total/v_subtotal else 1 end;

  for r in select * from public.erp_purchase_order_items_cloud
    where company_id=p_company_id and order_id=d.parent_id and not is_deleted order by id
  loop
    ac:=public.erp_v736_item_accounting(p_company_id,r.item_type,r.item_id,null);
    v_cost_currency:=upper(ac->>'costCurrency');
    perform public.erp_phase2_account_guard(p_company_id,ac->>'assetAccountId','asset',v_cost_currency);
    v_amount:=r.line_total*v_factor;
    v_converted:=public.erp_v736_convert_currency(v_amount,v_currency,v_cost_currency,v_order_rate);
    lines:=coalesce(v_by_currency->v_cost_currency,'[]'::jsonb)||jsonb_build_array(jsonb_build_object(
      'accountId',ac->>'assetAccountId','debit',v_converted,'credit',0,
      'description','مخزون شراء - '||r.description,'itemType',r.item_type,'itemId',r.item_id));
    v_by_currency:=jsonb_set(v_by_currency,array[v_cost_currency],lines,true);
  end loop;

  -- Retire journals generated by legacy capitalization-labelled engines. Their
  -- inventory layers and valuation snapshots remain; only accounting is replaced.
  if nullif(d.payload->>'journalEntryId','') is not null then
    v_old_ids:=array_append(v_old_ids,d.payload->>'journalEntryId');
  end if;
  for x in select value from jsonb_array_elements(coalesce(d.payload->'costJournalEntries','[]'::jsonb)) loop
    if nullif(x->>'journalEntryId','') is not null then v_old_ids:=array_append(v_old_ids,x->>'journalEntryId'); end if;
  end loop;
  update public.erp_journal_lines set is_deleted=true,deleted_at=now(),updated_at=now(),updated_by=auth.uid()
   where company_id=p_company_id and data->>'entryId'=any(v_old_ids) and not is_deleted;
  update public.erp_journal_entries set is_deleted=true,deleted_at=now(),updated_at=now(),updated_by=auth.uid()
   where company_id=p_company_id and id=any(v_old_ids) and not is_deleted;

  if (select count(*) from jsonb_object_keys(v_by_currency))=1 and v_by_currency ? v_currency then
    v_invoice_lines:=(v_by_currency->v_currency)||jsonb_build_array(jsonb_build_object(
      'accountId',v_supplier_account,'debit',0,'credit',v_total,
      'description','ذمة المورد - فاتورة شراء'));
    v_entry:=public.erp_phase2_insert_journal_at(
      p_company_id,'purchase_invoice',p_invoice_id::text,
      public.erp_next_document_number(p_company_id,'purchase_invoice_journal','PIJ',v_effective),
      'فاتورة شراء مباشرة إلى حسابات المخزون '||d.document_number,v_currency,v_invoice_lines,v_effective);
    v_entries:=jsonb_build_array(jsonb_build_object('currency',v_currency,'journalEntryId',v_entry,'mode','direct'));
  else
    v_settlement:=public.erp_v760_ensure_purchase_fx_settlement_accounts(p_company_id);
    v_settlement_id:=v_settlement->>v_currency;
    v_invoice_lines:=jsonb_build_array(
      jsonb_build_object('accountId',v_settlement_id,'debit',v_total,'credit',0,'description','تسوية عملة فاتورة الشراء'),
      jsonb_build_object('accountId',v_supplier_account,'debit',0,'credit',v_total,'description','ذمة المورد - فاتورة شراء'));
    v_entry:=public.erp_phase2_insert_journal_at(
      p_company_id,'purchase_invoice_fx_settlement',p_invoice_id::text||':invoice',
      public.erp_next_document_number(p_company_id,'purchase_invoice_journal','PIJ',v_effective),
      'فاتورة شراء متعددة العملات '||d.document_number,v_currency,v_invoice_lines,v_effective);
    v_entries:=v_entries||jsonb_build_array(jsonb_build_object('currency',v_currency,'journalEntryId',v_entry,'mode','supplier'));
    for k,lines in select key,value from jsonb_each(v_by_currency) loop
      v_settlement_id:=v_settlement->>k;
      lines:=lines||jsonb_build_array(jsonb_build_object(
        'accountId',v_settlement_id,'debit',0,
        'credit',(select coalesce(sum(public.erp_try_numeric(value->>'debit',0)),0) from jsonb_array_elements(lines)),
        'description','تسوية تحويل عملة المشتريات'));
      v_entry:=public.erp_phase2_insert_journal_at(
        p_company_id,'purchase_inventory_fx_settlement_'||lower(k),p_invoice_id::text||':'||k,
        public.erp_next_document_number(p_company_id,'purchase_inventory_journal_'||lower(k),'PIV',v_effective),
        'إثبات مخزون الشراء حسب التعريف '||d.document_number,k,lines,v_effective);
      v_entries:=v_entries||jsonb_build_array(jsonb_build_object('currency',k,'journalEntryId',v_entry,'mode','inventory'));
    end loop;
  end if;

  update public.erp_commercial_workflow_documents set
    payload=(payload-'journalEntryId'-'costJournalEntries')||jsonb_build_object(
      'journalEntryId',v_entries->0->>'journalEntryId','costJournalEntries',v_entries,
      'v760NoCapitalizationNormalized',true,'v760NormalizedAt',now(),
      'accountingPolicy','definition_accounts_no_capitalization'),updated_at=now(),updated_by=auth.uid()
   where company_id=p_company_id and id=p_invoice_id;
  return jsonb_build_object('ok',true,'journalEntries',v_entries);
end;
$$;

-- Repair PL/pgSQL record/table-alias shadowing in maintenance reversal.
create or replace function public.erp_v66_reverse_maintenance_stock(
  p_company_id uuid,p_order_id uuid,p_reason text default null
) returns void language plpgsql security definer set search_path=public as $$
declare
  o public.erp_maintenance_orders%rowtype; p record; s public.erp_warehouse_stock%rowtype;
  v_product_id text; v_warehouse_id text; v_issued numeric; v_returned numeric;
  v_restore numeric; v_now timestamptz:=now();
begin
  select * into o from public.erp_maintenance_orders
   where company_id=p_company_id and id=p_order_id and not is_deleted for update;
  if not found then raise exception 'maintenance_order_not_found'; end if;

  for p in
    select coalesce(source_product_id,product_id::text) product_id,
      coalesce(source_warehouse_id,warehouse_id::text,o.source_warehouse_id,o.warehouse_id::text) warehouse_id,
      max(product_name) product_name
    from public.erp_maintenance_parts
    where company_id=p_company_id and maintenance_order_id=p_order_id
      and not is_deleted and line_type<>'service'
    group by 1,2
  loop
    v_product_id:=p.product_id; v_warehouse_id:=p.warehouse_id;
    select coalesce(sum(abs(public.erp_try_numeric(data->>'quantity',0))),0) into v_issued
      from public.erp_inventory_movements
     where company_id=p_company_id and not is_deleted
       and coalesce(data->>'referenceId',data->>'reference_id')=p_order_id::text
       and lower(coalesce(data->>'referenceType',data->>'reference_type',''))='maintenance_order'
       and lower(coalesce(data->>'movementType',data->>'movement_type',''))='maintenance_out'
       and coalesce(data->>'productId',data->>'product_id')=v_product_id
       and coalesce(data->>'warehouseId',data->>'warehouse_id')=v_warehouse_id;
    select coalesce(sum(abs(public.erp_try_numeric(data->>'quantity',0))),0) into v_returned
      from public.erp_inventory_movements
     where company_id=p_company_id and not is_deleted
       and coalesce(data->>'referenceId',data->>'reference_id')=p_order_id::text
       and lower(coalesce(data->>'movementType',data->>'movement_type',''))='maintenance_return'
       and coalesce(data->>'productId',data->>'product_id')=v_product_id
       and coalesce(data->>'warehouseId',data->>'warehouse_id')=v_warehouse_id;
    v_restore:=greatest(v_issued-v_returned,0);
    if v_restore<=0 then continue; end if;
    s:=public.erp_inventory_ensure_stock(p_company_id,v_warehouse_id,v_product_id);
    update public.erp_warehouse_stock set data=data||jsonb_build_object(
      'quantity',public.erp_try_numeric(data->>'quantity',0)+v_restore,
      'updatedAt',v_now),updated_at=v_now,updated_by=auth.uid() where id=s.id;
    perform public.erp_inventory_insert_movement(
      p_company_id,v_product_id,v_warehouse_id,'maintenance_return',v_restore,0,
      'maintenance_cancel',p_order_id::text,coalesce(nullif(btrim(p_reason),''),'إلغاء صرف الصيانة'));
    perform public.erp_inventory_refresh_product(p_company_id,v_product_id);
  end loop;

  -- Future-proof cancellation if maintenance FIFO rows exist.
  update public.erp_inventory_cost_layers l set
    remaining_quantity=least(l.original_quantity,l.remaining_quantity+c.quantity),
    status='active',updated_at=v_now,updated_by=auth.uid()
  from public.erp_inventory_fifo_consumptions c
  where c.company_id=p_company_id and c.delivery_id=p_order_id and c.status='active' and l.id=c.layer_id;
  update public.erp_inventory_fifo_consumptions set status='reversed',reversed_at=v_now
   where company_id=p_company_id and delivery_id=p_order_id and status='active';
  perform public.erp_phase2_void_reference_journals(
    p_company_id,'maintenance_stock_issue',p_order_id::text);
end;
$$;

revoke all on function public.erp_deterministic_uuid(text) from public,anon;
grant execute on function public.erp_deterministic_uuid(text) to authenticated,service_role;
revoke all on function public.erp_transfer_cloud_cash(uuid,text,text,numeric,numeric,numeric,timestamptz,text) from public,anon;
grant execute on function public.erp_transfer_cloud_cash(uuid,text,text,numeric,numeric,numeric,timestamptz,text) to authenticated,service_role;
revoke all on function public.erp_v760_normalize_purchase_invoice_posting(uuid,uuid) from public,anon;
grant execute on function public.erp_v760_normalize_purchase_invoice_posting(uuid,uuid) to authenticated,service_role;
revoke all on function public.erp_v66_reverse_maintenance_stock(uuid,uuid,text) from public,anon;
grant execute on function public.erp_v66_reverse_maintenance_stock(uuid,uuid,text) to authenticated,service_role;

notify pgrst,'reload schema';
commit;
