begin;

-- 17.54 cash-document integrity hardening.
-- Manual cash vouchers remain editable/deletable, while vouchers generated by
-- expenses, invoices, purchases or transfers can only be changed through their
-- owning document. This prevents orphaned documents and ledger mismatches.
create or replace function public.erp_post_cloud_cash_transaction(
  p_company_id uuid,p_transaction jsonb,p_replace boolean default false
) returns void language plpgsql security definer set search_path=public as $$
declare
  v_id text:=trim(coalesce(p_transaction->>'id',''));
  v_cash_id text:=trim(coalesce(p_transaction->>'cashAccountId',''));
  v_counter_id text:=trim(coalesce(p_transaction->>'counterAccountId',''));
  v_voucher text:=trim(coalesce(p_transaction->>'voucherNumber',''));
  v_type text:=lower(trim(coalesce(p_transaction->>'type','')));
  v_currency text:=upper(trim(coalesce(p_transaction->>'currency','')));
  v_reference_type text:=lower(trim(coalesce(p_transaction->>'referenceType','manual_cash_transaction')));
  v_reference_id text:=nullif(trim(coalesce(p_transaction->>'referenceId','')),'');
  v_amount numeric:=coalesce((p_transaction->>'amount')::numeric,0);
  v_transaction_date timestamptz;
  v_cash public.erp_cash_accounts%rowtype;
  v_journal_id text:=gen_random_uuid()::text;
  v_old_journal text;
  v_old_reference_type text;
  v_old_reference_id text;
  v_now timestamptz:=now();
  v_cash_debit numeric:=0;
  v_cash_credit numeric:=0;
  v_cash_account record;
  v_counter record;
  v_payload jsonb;
begin
  if not public.can_manage_master_data(p_company_id) then raise exception 'access denied'; end if;

  begin
    v_transaction_date:=(p_transaction->>'transactionDate')::timestamptz;
  exception when others then
    raise exception 'تاريخ حركة الصندوق غير صحيح';
  end;

  if v_id='' or v_voucher='' or v_cash_id='' or v_counter_id='' or
     v_amount<=0 or v_type not in ('receipt','payment') or v_currency='' or
     v_transaction_date is null then
    raise exception 'بيانات حركة الصندوق غير صحيحة';
  end if;

  -- Serialize voucher-number checks per company to prevent concurrent duplicates.
  perform pg_advisory_xact_lock(hashtextextended(p_company_id::text||':'||lower(v_voucher),0));
  if exists(
    select 1 from public.erp_cash_transactions
    where company_id=p_company_id and not is_deleted and id<>v_id
      and lower(trim(data->>'voucherNumber'))=lower(v_voucher)
  ) then
    raise exception 'رقم السند مستخدم مسبقاً';
  end if;

  select * into v_cash from public.erp_cash_accounts
  where company_id=p_company_id and id=v_cash_id and not is_deleted for update;
  if not found or not coalesce((v_cash.data->>'isActive')::boolean,true) then
    raise exception 'الصندوق غير موجود أو غير فعال';
  end if;
  if upper(trim(coalesce(v_cash.data->>'currency','')))<>v_currency then
    raise exception 'عملة السند لا تطابق عملة الصندوق';
  end if;

  select account_id,code,name,currency into v_cash_account
  from public.erp_accounts
  where organization_id=p_company_id and account_id=v_cash.data->>'accountId' and is_active;
  select account_id,code,name,currency into v_counter
  from public.erp_accounts
  where organization_id=p_company_id and account_id=v_counter_id and is_active;
  if v_cash_account.account_id is null or v_counter.account_id is null then
    raise exception 'الحساب المحاسبي غير موجود أو غير فعال';
  end if;
  if v_cash_account.account_id=v_counter.account_id then
    raise exception 'الحساب المقابل يجب أن يختلف عن حساب الصندوق';
  end if;
  if upper(coalesce(v_cash_account.currency,'')) not in (v_currency,'MULTI') then
    raise exception 'عملة حساب الصندوق لا تطابق عملة السند';
  end if;
  if upper(coalesce(v_counter.currency,'')) not in (v_currency,'MULTI') then
    raise exception 'عملة الحساب المقابل لا تطابق عملة السند';
  end if;

  select data->>'journalEntryId',lower(trim(coalesce(data->>'referenceType','manual_cash_transaction'))),data->>'referenceId'
    into v_old_journal,v_old_reference_type,v_old_reference_id
  from public.erp_cash_transactions
  where company_id=p_company_id and id=v_id and not is_deleted for update;

  if p_replace and v_old_journal is null then
    raise exception 'لم يتم العثور على حركة الصندوق المطلوبة';
  end if;
  if not p_replace and v_old_journal is not null then
    raise exception 'رقم الحركة مستخدم مسبقاً';
  end if;
  if p_replace and v_old_reference_type<>'manual_cash_transaction' then
    raise exception 'لا يمكن تعديل حركة مرتبطة مباشرة؛ عدّل المستند الأصلي';
  end if;
  if p_replace and v_reference_type<>'manual_cash_transaction' then
    raise exception 'لا يمكن تحويل الحركة اليدوية إلى حركة مرتبطة';
  end if;
  if v_reference_type<>'manual_cash_transaction' and v_reference_id is null then
    raise exception 'مرجع المستند المرتبط مطلوب';
  end if;

  if v_old_journal is not null then
    update public.erp_journal_lines
      set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
    where company_id=p_company_id and not is_deleted and data->>'entryId'=v_old_journal;
    update public.erp_journal_entries
      set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
    where company_id=p_company_id and id=v_old_journal and not is_deleted;
  end if;

  v_payload:=p_transaction||jsonb_build_object(
    'id',v_id,'voucherNumber',v_voucher,'type',v_type,'currency',v_currency,
    'transactionDate',v_transaction_date,'referenceType',v_reference_type,
    'referenceId',v_reference_id,'journalEntryId',v_journal_id,'updatedAt',v_now
  );

  insert into public.erp_cash_transactions(company_id,id,data,created_by,updated_by)
  values(p_company_id,v_id,v_payload,auth.uid(),auth.uid())
  on conflict(company_id,id) do update set
    data=excluded.data,is_deleted=false,deleted_at=null,updated_at=v_now,updated_by=auth.uid();

  if v_type='receipt' then v_cash_debit:=v_amount; else v_cash_credit:=v_amount; end if;

  insert into public.erp_journal_entries(company_id,id,data,created_by,updated_by)
  values(p_company_id,v_journal_id,jsonb_build_object(
    'id',v_journal_id,'entryNumber','CASH-'||v_voucher,
    'entryDate',v_transaction_date,
    'description',case when v_type='receipt' then 'قبض نقدي' else 'صرف نقدي' end||' - '||coalesce(p_transaction->>'category',''),
    'currency',v_currency,'referenceType',v_reference_type,'referenceId',coalesce(v_reference_id,v_id),
    'cashTransactionId',v_id,'totalDebit',v_amount,'totalCredit',v_amount,
    'status','posted','createdAt',v_now
  ),auth.uid(),auth.uid());

  insert into public.erp_journal_lines(company_id,id,data,created_by,updated_by) values
  (p_company_id,gen_random_uuid()::text,jsonb_build_object(
    'entryId',v_journal_id,'accountId',v_cash_account.account_id,
    'accountCode',v_cash_account.code,'accountName',v_cash_account.name,
    'currency',v_currency,'referenceType',v_reference_type,
    'referenceId',coalesce(v_reference_id,v_id),'cashTransactionId',v_id,
    'debit',v_cash_debit,'credit',v_cash_credit,
    'description',coalesce(p_transaction->>'notes','')
  ),auth.uid(),auth.uid()),
  (p_company_id,gen_random_uuid()::text,jsonb_build_object(
    'entryId',v_journal_id,'accountId',v_counter.account_id,
    'accountCode',v_counter.code,'accountName',v_counter.name,
    'currency',v_currency,'referenceType',v_reference_type,
    'referenceId',coalesce(v_reference_id,v_id),'cashTransactionId',v_id,
    'debit',v_cash_credit,'credit',v_cash_debit,
    'description',coalesce(p_transaction->>'notes','')
  ),auth.uid(),auth.uid());
end $$;

create or replace function public.erp_delete_cloud_cash_transaction(
  p_company_id uuid,p_transaction_id text
) returns void language plpgsql security definer set search_path=public as $$
declare
  v_journal text;
  v_reference_type text;
  v_now timestamptz:=now();
begin
  if not public.can_manage_master_data(p_company_id) then raise exception 'access denied'; end if;
  select data->>'journalEntryId',lower(trim(coalesce(data->>'referenceType','manual_cash_transaction')))
    into v_journal,v_reference_type
  from public.erp_cash_transactions
  where company_id=p_company_id and id=p_transaction_id and not is_deleted for update;
  if v_journal is null then raise exception 'لم يتم العثور على حركة الصندوق المطلوبة'; end if;
  if v_reference_type<>'manual_cash_transaction' then
    raise exception 'لا يمكن حذف حركة مرتبطة مباشرة؛ احذف المستند الأصلي';
  end if;

  update public.erp_cash_transactions
    set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
  where company_id=p_company_id and id=p_transaction_id and not is_deleted;
  update public.erp_journal_entries
    set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
  where company_id=p_company_id and id=v_journal and not is_deleted;
  update public.erp_journal_lines
    set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
  where company_id=p_company_id and data->>'entryId'=v_journal and not is_deleted;
end $$;

-- Delete a transfer as one accounting document. Both cash movements and both
-- journals are reversed together, so balances and reconciliation stay aligned.
create or replace function public.erp_delete_cloud_cash_transfer(
  p_company_id uuid,p_transfer_id text
) returns void language plpgsql security definer set search_path=public as $$
declare
  v_now timestamptz:=now();
  v_transaction record;
begin
  if not public.can_manage_master_data(p_company_id) then raise exception 'access denied'; end if;
  if not exists(
    select 1 from public.erp_cash_transfers
    where company_id=p_company_id and id=p_transfer_id and not is_deleted for update
  ) then raise exception 'لم يتم العثور على التحويل المطلوب'; end if;

  for v_transaction in
    select id,data->>'journalEntryId' as journal_id
    from public.erp_cash_transactions
    where company_id=p_company_id and not is_deleted
      and lower(coalesce(data->>'referenceType',''))='cash_transfer'
      and data->>'referenceId'=p_transfer_id
    for update
  loop
    update public.erp_journal_lines
      set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
    where company_id=p_company_id and not is_deleted and data->>'entryId'=v_transaction.journal_id;
    update public.erp_journal_entries
      set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
    where company_id=p_company_id and id=v_transaction.journal_id and not is_deleted;
    update public.erp_cash_transactions
      set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
    where company_id=p_company_id and id=v_transaction.id and not is_deleted;
  end loop;

  update public.erp_cash_transfers
    set is_deleted=true,deleted_at=v_now,updated_at=v_now,updated_by=auth.uid()
  where company_id=p_company_id and id=p_transfer_id and not is_deleted;
end $$;

grant execute on function public.erp_post_cloud_cash_transaction(uuid,jsonb,boolean) to authenticated;
grant execute on function public.erp_delete_cloud_cash_transaction(uuid,text) to authenticated;
grant execute on function public.erp_delete_cloud_cash_transfer(uuid,text) to authenticated;

commit;
