-- Generated by SETUP_CLOUD_v15.81.2.ps1. Safe and idempotent.
select public.bootstrap_company_admin(
  CAST('11111111-1111-4111-8111-111111111111' AS uuid),
  'PlAQuu84tiQcqnqd7ToBliEr0Ac2',
  'ajkinbaghdad@gmail.com',
  'System Administrator',
  null,
  'owner'
);
